spring:
  datasource:
    username: admin
    password: admin
    url: jdbc:postgresql://postgres:5432/reports
    driver-class-name: org.postgresql.Driver
  jpa:
    generate-ddl: true

# Total time: 195815ms
# Start time:  4.315s

# ./mvnw -Pnative spring-boot:build-image
